version: '2'

services:
  elasticsearch:
    image: elasticsearch:2
    container_name: elk_elasticsearch
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - logging

  logstash:
    image: logstash:2
    container_name: elk_logstash
    ports:
      - "5000:5000/udp"
    volumes:
      - ./config/logstash:/opt/logstash/conf.d
    command: -f /opt/logstash/conf.d/logstash.conf
    networks:
      - logging

  kibana:
    image: kibana:4
    container_name: elk_kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
    networks:
      - logging

  nginx:
    image: nginx:stable
    container_name: elk_nginx
    ports:
      - "5600:5600"
    volumes:
      - ./config/nginx/kibana.conf:/etc/nginx/conf.d/kibana.conf
      - ./config/nginx/kibana:/etc/nginx/kibana
    depends_on:
      - kibana
    networks:
      - logging

networks:
  logging:
